import 'dart:convert';

/// Pulls the pass code out of whatever a QR actually encodes.
///
/// The pass QR is generated by the backend, and a QR of this kind is encoded
/// three different ways depending on who generated it: the bare code, a JSON
/// object, or a check-in URL with the code in the query. `/verify` and
/// `/lookup` only ever take the bare code, so everything is reduced to that
/// here rather than in the scanner.
class VisitorPassCode {
  const VisitorPassCode._();

  /// Keys a JSON payload may carry the code under.
  static const List<String> _keys = [
    'passCode',
    'pass_code',
    'visitorPassCode',
    'code',
    'passcode',
  ];

  /// The code inside [scanned], or null when there is nothing usable in it.
  static String? extract(String? scanned) {
    final raw = (scanned ?? '').trim();
    if (raw.isEmpty) return null;

    final fromJson = _fromJson(raw);
    if (fromJson != null) return fromJson;

    final fromUri = _fromUri(raw);
    if (fromUri != null) return fromUri;

    final fromLabel = _fromLabelledText(raw);
    if (fromLabel != null) return fromLabel;

    // A bare code. Anything with whitespace or newlines is text the scanner
    // could not make sense of, and sending it would only earn a 404.
    if (RegExp(r'^[A-Za-z0-9_\-]{4,64}$').hasMatch(raw)) return raw;

    return null;
  }

  static String? _fromJson(String raw) {
    if (!raw.startsWith('{')) return null;
    try {
      final decoded = jsonDecode(raw);
      if (decoded is! Map) return null;
      for (final key in _keys) {
        final value = decoded[key];
        final text = value?.toString().trim() ?? '';
        if (text.isNotEmpty) return text;
      }
    } catch (_) {
      // Not JSON after all — fall through to the other shapes.
    }
    return null;
  }

  static String? _fromUri(String raw) {
    if (!raw.startsWith('http://') && !raw.startsWith('https://')) return null;

    final uri = Uri.tryParse(raw);
    if (uri == null) return null;

    for (final key in _keys) {
      final value = uri.queryParameters[key]?.trim();
      if (value != null && value.isNotEmpty) return value;
    }

    // `…/visitor-passes/NS-4821` — the last segment is the code.
    final segments = uri.pathSegments
        .where((segment) => segment.trim().isNotEmpty)
        .toList();
    if (segments.isEmpty) return null;

    final last = segments.last.trim();
    return RegExp(r'^[A-Za-z0-9_\-]{4,64}$').hasMatch(last) ? last : null;
  }

  /// Reads `Pass code: NS-4821` out of a multi-line text QR — the shape the
  /// shared pass itself uses.
  static String? _fromLabelledText(String raw) {
    final match = RegExp(
      r'pass\s*code\s*[:\-]\s*([A-Za-z0-9_\-]{4,64})',
      caseSensitive: false,
    ).firstMatch(raw);
    return match?.group(1)?.trim();
  }
}
