name: nahata_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.1+8


environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.8
#  flutter_lints: ^5.0.0
#  http: ^0.13.6
#  razorpay_flutter: ^1.3.5
#  provider: ^6.1.1
#  intl: 0.20.2
#  shared_preferences: ^2.2.2
#  table_calendar: ^3.0.9
#  flutter_launcher_icons:
#  connectivity_plus:
#  qr_code_scanner_plus: ^2.0.10+1
#  image_picker:
#  url_launcher:
#  device_preview:
#  get:
#  cached_network_image:
#  share_plus: ^10.0.2
#  flutter_svg:
#  path_provider:
#  html_unescape: ^2.0.0
  cupertino_icons: ^1.0.8
  image_picker:
  shared_preferences: ^2.2.2
  html_unescape:
  http:
  razorpay_flutter: ^1.3.6
  share_plus:
  path_provider:
  intl:
  html:
  geolocator:
  flutter_map: ^7.0.0
  latlong2:
  carousel_slider:
  url_launcher:
  connectivity_plus:
  cached_network_image:
  webview_flutter: ^4.13.0
  qr_code_scanner_plus:
  permission_handler:
  image_gallery_saver_plus:
  qr_flutter:
#  file_picker: ^6.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/nahataappicon.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/nahataimg.png
    - assets/images/nahata.webp
    - assets/images/logout1.webp
    - assets/images/nahata_a.webp
    - assets/images/1.webp
    - assets/images/2.webp
    - assets/images/3.webp
    - assets/r1.png
    - assets/r2.png
    - assets/r3.png
    - assets/r4.png
    - assets/r5.png
    - assets/r6.png
    - assets/ns.png
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/cricket.png
    - assets/bad.jpg
    - assets/12.png
    - assets/23.webp
    - assets/56.jpg
    - assets/g.png
    - assets/image.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poltawski Nowy
      fonts:
        - asset: assets/fonts/PoltawskiNowyBold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/InterLight.ttf
          weight: 300
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
